spring:
  datasource:
    url: jdbc:mysql://localhost:13306/smartorm_demo?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: io.github.forgottenlab.smartorm.demo.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    io.github.forgottenlab.smartorm: debug
    org.mybatis: debug